---
  - name: Move the directory for building the docker image to the host
    synchronize:
      src: ../../elter-data-node
      dest: /opt/

  - name: Push the datasource properties file to the remote machine with the specified credentials
    template:
      src: datasource.properties.j2
      dest: /opt/elter-data-node/sos-node/base-image/sos-config/datasource.properties
      owner: root
      group: docker
      mode: 550

  - name: Push the old api helg settings file to the remote machine
    template:
      src: helg-settings-old-api.json.j2
      dest: /opt/elter-data-node/sos-node/base-image/sos-config/helg-settings.json
      owner: root
      group: docker
      mode: 550
    when: sos_version == "4-3-15"

  - name: Push the new api helg settings file to the remote machine
    template:
      src: helg-settings.json.j2
      dest: /opt/elter-data-node/sos-node/base-image/sos-config/helg-settings.json
      owner: root
      group: docker
      mode: 550
    when: sos_version != "4-3-15"

  - name: Push the old client settings file to the remote machine
    template:
      src: settings.json.j2
      dest: /opt/elter-data-node/sos-node/base-image/sos-config/settings.json
      owner: root
      group: docker
      mode: 550
