version: '2'
services:
  postgresql-node:
    build: postgresql-node/.
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
  sos-service:
    build: sos-node/.
    ports:
      - 8080:8080
    links:
      - postgresql-node:postgres
