version: '3'

services:

  postgresql-node:
    build: postgresql-node/sos-4-4-1/.
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_volume:/var/lib/postgresql/data/pgdata

  sos-service:
    build: sos-node/sos-4-4-1/.
    ports:
      - 80:8080
    links:
      - postgresql-node:postgres

volumes:
  pg_volume:
