---
- hosts: sos-4-4-1-hosts
  remote_user: root
  roles:
    - disk-setup
    - docker-setup
    - sos-node
  vars:
    docker_compose_version: 1.14.0
    sos_version: 4-4-1
    # Placed here, but probably there is a better way to do this
    postgres_user: pg-username-here
    postgres_password: pg-password-here
    min_connections: 5
    max_connections: 7