---
- hosts: sos-4-3-hosts
  remote_user: root
  roles:
    - jasmin-node
    - sos-node
  vars:
    docker_compose_version: 1.14.0
    sos_version: 4-3-15
    # Placed here, but probably there is a better way to do this
    postgres_user: postgres
    postgres_password: postgres
